### ISSUE TITLE
Issue building the project

### ISSUE THREAD

**Issue by lintolinton** [GerathenAI/MISSING-PERSONS-DATABASE-2024-KENYA-FINANCE-BILL-PROTESTS-#4]
Has anyone been able to build the project from docker? Seems like some files are missing

**Comment by Mtsumi** [comment]
It is conflicting packages kwa req.txt

**Comment by lintolinton** [comment]
> It is conflicting packages kwa req.txt

have you been able to resolve it

**Comment by lintolinton** [comment]
halafu in the Dockerfile, it's attempting to execute this file, app.py which doesn't exist. I think she meant App.py?

CMD ["python", "app.py"]

**Comment by Mtsumi** [comment]
Use these in req.txt
```
Flask
Flask-SQLAlchemy==3.0.2
pytest==6.2.5
gunicorn==20.1.0
psycopg2-binary==2.9.3
requests==2.26.0
Werkzeug==2.2.2
```
And then in App.py, update the models import by using app.models
Then replace the if statement to this
```
if __name__ == '__main__':
    with app.app_context():
        db.create_all()
    app.run(debug=True)
```

Finally update app.py in Dockerfile to App.py

**Comment by wathika-eng** [comment]
> Has anyone been able to build the project from docker? Seems like some files are missing

You can use this => https://gist.github.com/wathika-eng/c186e99fec5e98bdc72bfd0d1559b178
